name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
      # you can specify actions. After "@", you can spefify the version, branch, or commit.
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John

      - name: Log Greeting Time
        run: echo"${{ steps.greet.output.time}}""