# The name of this workflow
name: Shell Commands

# build trigger(s)
on: [push]

# jobs to run
jobs: 
# the name of the job
  run-shell-command: 
    runs-on: ubuntu-latest
    # the steps for this specific job to run
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: python